### ISSUE TITLE
There's any way to load the typescript example without jquery?

### ISSUE THREAD

**Issue by mhosman** [moozzyk/SignalRChat#3]

**Comment by moozzyk** [comment]
jQuery is needed just to tweak UI and is there because I was migrating the official sample for the previous version of SignalR to Core. You can't run the sample without jQuery unless you modify the code that uses jquery to tweak UI. (Read more here: https://blog.3d-logic.com/2017/09/18/the-signalr-for-asp-net-core-javascript-client-part-1-web-applications/)
If you are trying to get rid of it because you are missing a dependency - make sure you run `npm install` first and it will install everything you need to run the sample, including jquery.
